### PR TITLE
[release-0.2] Fix: e2e tests 

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:
Cherry-pick for https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/260

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Review by furkatgofurov7 — DISMISSED** [review]

**Review by richardcase — CHANGES_REQUESTED** [review]

**Comment by Danil-Grigorev** [comment]
@richardcase @furkatgofurov7 Updated, PTAL again

**Review by furkatgofurov7 — COMMENTED** [review]
lgtm

**Review by salasberryfin — DISMISSED** [review]

**Review by richardcase — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
@Danil-Grigorev just to confirm, have we run e2e tests with these changes?

**Comment by Danil-Grigorev** [comment]
There are some issues with e2e tests on release-0.2 branch, unrelated to any recently merged change. Docker provider fails to update ProviderID field on the machine. Needs to be looked into, just didn’t find time yet

**Comment by furkatgofurov7** [comment]
maybe https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/203 needs to be backported?

**Comment by richardcase** [comment]
> maybe #203 needs to be backported?

Yes i think part or all of it my need backporting.....especially this part

```yaml
  serverConfig:
    disableComponents:
      kubernetesComponents:
      - cloudController
```

**Comment by Danil-Grigorev** [comment]
Tests are passing locally with the change 
image

**Comment by furkatgofurov7** [comment]
@Danil-Grigorev strange, I noticed space issue in the logs in GHA, maybe we can push https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/204 also on top of current changes and retest?

**Comment by richardcase** [comment]
> @Danil-Grigorev strange, I noticed space issue in the logs in GHA, maybe we can push #204 also on top of current changes and retest?

We could also move to self hosted runners for the e2e. I started to do this but we need to update the VM image.

**Comment by Danil-Grigorev** [comment]
Currently tests are already running longer then before. I think this all fixes e2e completely for now (24GB were freed from the logs), PTAL @furkatgofurov7 @richardcase

**Review by furkatgofurov7 — APPROVED** [review]
Thanks for working on this @Danil-Grigorev!

/approve

**Review by alexander-demicev — APPROVED** [review]

**Pull request merged**
